# https://taskfile.dev

version: '3'

includes:
  hway:
    taskfile: ./taskfiles/hway.yml
  ipfs:
    taskfile: ./taskfiles/ipfs.yml
  postgres:
    taskfile: ./taskfiles/postgres.yml
  sonrd:
    taskfile: ./taskfiles/sonrd.yml
  synapse:
    taskfile: ./taskfiles/synapse.yml
  tigerbeetle:
    taskfile: ./taskfiles/tigerbeetle.yml

tasks:
  default:
    cmds:
      - task: task -l
